[package]
name = "zflow_runtime"
version = "0.1.0"
edition = "2021"
authors = ["Damilare Akinlaja <dreakinlaja@gmail.com>"]
license = "MIT"
description = "ZFlow FBP Graph Runtime"
keywords = ["fbp", "flowbased", "low-code", "no-code", "visual-programming"]


[dependencies]
zflow_graph = {path = "../zflow_graph"}
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
cast_trait_object = "0.1.3"
foreach = "0.3.0"
fp_rust = {version = "0.3.5", features = ["for_futures"]}
rayon = "1.7.0"
futures = {version = "0.3.25", features = ["thread-pool"] }
futures-util = "0.2.1"
assert-json-diff = "2.0.2"
beady = "0.6.0"
regex = "1.7.1"
log = "0.4"
env_logger = "0.10.0"
poll-promise = {git="https://github.com/EmbarkStudios/poll-promise", version="0.2.0"}
array_tool = "1.0.3"
dyn-clone = "1.0.11"
is-url = "1.0.4"
extism = "0.5.0"
wasmtime = "10.0.0"
anyhow = "1.0.71"
bincode = "1.3.3"
rquickjs = {version = "0.1.7", features = ["exports", "async-std", "rust-alloc", "loader", "dyn-load"]}
rlua = "0.19.7"
once_cell = "1.18.0"
rlua_serde = {git="https://github.com/darmie/rlua_serde", branch="master"}
ruwren = {git="https://github.com/darmie/ruwren"}


[lib]
doctest = false



