[package]
name = "zflow"
version = "0.1.1"
edition = "2021"
authors = ["Damilare Akinlaja <dreakinlaja@gmail.com>"]
license = "MIT"
description = "FBP Graph Library for Rust"
keywords = ["fbp", "flowbased", "low-code", "no-code", "visual-programming"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
foreach = "0.3.0"
nuid = "0.3.2"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
beady = "0.6.0"
futures = "0.3"
assert-json-diff = "2.0.2"

[lib]
doctest = false