[package]
name = "fbp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex-lexer = "0.2.0"
regex = "1.8.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
